# Generated by Django 4.2.3 on 2023-07-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demotravelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
