# Generated by Django 4.2.3 on 2023-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotravelapp', '0003_rename_desc_team_desc1_rename_img_team_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img1',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
