# Generated by Django 4.2.3 on 2023-07-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotravelapp', '0004_alter_team_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
