# Generated by Django 4.2.3 on 2023-07-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demotravelapp', '0005_alter_place_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='team',
            name='img1',
            field=models.ImageField(upload_to='image'),
        ),
    ]
