# Generated by Django 4.2.5 on 2023-09-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_remove_branch_wikipedia_link_alter_branch_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='wikipedia_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
